# Generated by Django 4.2 on 2023-05-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id', 'primeiro_nome', 'ultimo_nome']},
        ),
    ]
